# Chapter 5 - Dimensionality Reduction Methods

## Segment 1 - Explanatory factor analysis

In [1]:
import pandas as pd
import numpy as np

import sklearn
from sklearn.decomposition import FactorAnalysis

from sklearn import datasets

### Factor analysis on does dataset

In [2]:
does = pd.read_csv('1_readonly/Services.csv')

X = does.iloc[:,:11]
variable_names = X.columns

X[0:10]

,Age_AtReg,Disability,Gender,CitizenStatus,EducationLevel,Race_Hispanic,Race_NativeAmerican,Race_Asian,Race_AfricanAmerican,Race_PacificIslander,Race_White
0,40,0,1,1,11,0,0,0,0,0,0
1,40,0,1,1,11,0,0,0,0,0,0
2,50,0,1,1,14,0,0,0,1,0,0
3,50,0,1,1,14,0,0,0,1,0,0
4,53,0,1,1,14,0,0,0,1,0,0
5,53,0,1,1,14,0,0,0,1,0,0
6,53,0,1,1,14,0,0,0,1,0,0
7,54,0,1,1,18,0,0,0,1,0,0
8,54,0,1,1,18,0,0,0,1,0,0
9,43,1,1,1,17,0,0,0,1,0,0

In [3]:
factor = FactorAnalysis().fit(X)

DF = pd.DataFrame(factor.components_, columns=variable_names)
print(DF)

    Age_AtReg  Disability    Gender  CitizenStatus  EducationLevel  \
0   13.030424    0.023275 -0.020529       0.002916        0.815610
1    0.213230   -0.002433 -0.064285      -0.003602       -3.393582
2   -0.001573    0.005306  0.014121       0.044801       -0.035698
3   -0.000194    0.017509 -0.003309      -0.046666        0.000937
4    0.001197   -0.017288  0.016961       0.016320        0.000588
5   -0.000756    0.008172 -0.040172       0.008766        0.003231
6   -0.000000    0.000000  0.000000       0.000000       -0.000000
7    0.000000    0.000000  0.000000       0.000000        0.000000
8    0.000000    0.000000 -0.000000      -0.000000        0.000000
9    0.000000    0.000000 -0.000000      -0.000000        0.000000
10   0.000000   -0.000000  0.000000       0.000000        0.000000

    Race_Hispanic  Race_NativeAmerican  Race_Asian  Race_AfricanAmerican  \
0        0.000522             0.000111    0.000318             -0.020812
1       -0.002772            -0.003361   -0.002821              0.042020
2        0.042787             0.025923    0.013283             -0.140291
3       -0.013421             0.020101    0.006368              0.025303
4        0.001485            -0.004196    0.006556              0.006278
5        0.000858            -0.002342    0.001498              0.001957
6        0.000000            -0.000000    0.000000             -0.000000
7       -0.000000             0.000000   -0.000000              0.000000
8        0.000000            -0.000000   -0.000000             -0.000000
9        0.000000             0.000000    0.000000              0.000000
10       0.000000            -0.000000    0.000000              0.000000

    Race_PacificIslander  Race_White
0              -0.000790    0.008429
1              -0.000070   -0.016997
2               0.006976    0.063787
3               0.008115    0.002012
4               0.003510   -0.010337
5               0.000553   -0.001865
6              -0.000000   -0.000000
7               0.000000   -0.000000
8               0.000000   -0.000000
9              -0.000000   -0.000000
10             -0.000000    0.000000